branch-defaults:
  deployment-project:
    environment: test3-dev
    group_suffix: null
  master:
    environment: test3-dev
    group_suffix: null
environment-defaults:
  Test3-env:
    branch: null
    repository: null
global:
  application_name: udagram_api
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: ./www/Archive.zip
